name: Lint Check

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Check code with ESLint
        run: npm run lint

      - name: Check code with svelte-check
        run: npm run check
